### ISSUE TITLE
[error] Uncaught Error: Call to a member function make() on null

### ISSUE THREAD

**Issue by xaboy** [top-think/think-swoole#140]
运行一段时间后自动报错
```
[error] [1]Uncaught Error: Call to a member function make() on null in /path/vendor/topthink/think-swoole/src/concerns/InteractsWithPools.php:25
Stack trace:
#0 /path/vendor/topthink/think-swoole/src/concerns/InteractsWithPools.php(50): think\swoole\Manager->getPools()
#1 /path/vendor/topthink/framework/src/think/Container.php(292): think\swoole\Manager->think\swoole\concerns\{closure}()
#2 /path/vendor/topthink/framework/src/think/Container.php(356): think\Container->invokeFunction(Object(Closure), Array)
#3 /path/vendor/topthink/framework/src/think/Event.php(260): think\Container->invoke(Object(Closure), Array)
#4 /path/vendor/topthink/framework/src/think/Event.php(221): think\Event->dispatch(Object(Closure), Array)
#5 /path/vendor/topthink/think-swoole/src/concerns/With[/web/wwwroot/mer.crmeb.net/crmeb_merchant/vendor/topthink/think-swoole/src/concerns/InteractsWithPools.php:25]
```

**Comment by yunwuxin** [comment]
这个有办法重现吗

**Comment by yunwuxin** [comment]
已修正

**Comment by xinson** [comment]
哪个版本修复了！我们用的是3.0！
