### ISSUE TITLE
报错反馈

### ISSUE THREAD

**Issue by HyperLife1119** [top-think/think-swoole#153]
```
PHP Fatal error:  Uncaught think\exception\ErrorException: Trying to access array offset on value of type null in /www/wwwroot/xxxxx/vendor/topthink/framework/src/think/console/output/driver/Console.php:205
Stack trace:
#0 /www/wwwroot/xxxxx/vendor/topthink/framework/src/think/console/output/driver/Console.php(205): think\initializer\Error->appError()
#1 /www/wwwroot/xxxxx/vendor/topthink/framework/src/think/console/output/driver/Console.php(180): think\console\output\driver\Console->getSttyColumns()
#2 /www/wwwroot/xxxxx/vendor/topthink/framework/src/think/console/output/driver/Console.php(145): think\console\output\driver\Console->getTerminalDimensions()
#3 /www/wwwroot/xxxxx/vendor/topthink/framework/src/think/console/output/driver/Console.php(82): think\console\output\driver\Console->getTerminalWidth()
#4 /www/wwwroot/xxxxx/vendor/topthink/framework/src/think/console/Output.php(167): think\console\output\driver\Console->renderExceptio in /www/wwwroot/xxxxx/vendor/topthink/framework/src/think/console/output/driver/Console.php on line 205
```

开启了协程，生产环境

**Comment by HyperLife1119** [comment]
```
PHP Fatal error:  Uncaught Error: Call to a member function make() on null in /www/wwwroot/api.chat.hypergo.net/vendor/topthink/think-swoole/src/concerns/InteractsWithPools.php:25
Stack trace:
#0 /www/wwwroot/api.chat.hypergo.net/vendor/topthink/think-swoole/src/concerns/InteractsWithPools.php(50): think\swoole\Manager->getPools()
#1 /www/wwwroot/api.chat.hypergo.net/vendor/topthink/framework/src/think/Container.php(292): think\swoole\Manager->think\swoole\concerns\{closure}()
#2 /www/wwwroot/api.chat.hypergo.net/vendor/topthink/framework/src/think/Container.php(356): think\Container->invokeFunction()
#3 /www/wwwroot/api.chat.hypergo.net/vendor/topthink/framework/src/think/Event.php(260): think\Container->invoke()
#4 /www/wwwroot/api.chat.hypergo.net/vendor/topthink/framework/src/think/Event.php(221): think\Event->dispatch()
#5 /www/wwwroot/api.chat.hypergo.net/vendor/topthink/think-swoole/src/concerns/WithApplication.php(45): think\Event->trigger()
#6 /www/wwwroot/api.chat.hypergo.net/vendor/topthink/think-swoole/src/concerns in /www/wwwroot/api.chat.hypergo.net/vendor/topthink/think-swoole/src/concerns/InteractsWithPools.php on line 25
```

**Comment by HyperLife1119** [comment]
```
PHP Fatal error:  Uncaught Error: Call to a member function make() on null in /www/wwwroot/xxxxx/vendor/topthink/think-swoole/src/concerns/InteractsWithPools.php:25
Stack trace:
#0 /www/wwwroot/xxxxx/vendor/topthink/think-swoole/src/concerns/InteractsWithPools.php(50): think\swoole\Manager->getPools()
#1 /www/wwwroot/xxxxx/vendor/topthink/framework/src/think/Container.php(292): think\swoole\Manager->think\swoole\concerns\{closure}()
#2 /www/wwwroot/xxxxx/vendor/topthink/framework/src/think/Container.php(356): think\Container->invokeFunction()
#3 /www/wwwroot/xxxxx/vendor/topthink/framework/src/think/Event.php(260): think\Container->invoke()
#4 /www/wwwroot/xxxxx/vendor/topthink/framework/src/think/Event.php(221): think\Event->dispatch()
#5 /www/wwwroot/xxxxx/vendor/topthink/think-swoole/src/concerns/WithApplication.php(45): think\Event->trigger()
#6 /www/wwwroot/xxxxx/vendor/topthink/think-swoole/src/concerns in /www/wwwroot/xxxxx/vendor/topthink/think-swoole/src/concerns/InteractsWithPools.php on line 25
```

**Comment by yunwuxin** [comment]
使用最新的开发版

**Comment by HyperLife1119** [comment]
最新的开发版在PHP7.4，生产环境下似乎无法运行，报很多错

**Comment by yunwuxin** [comment]
最新的开发版 和v3.0.8在环境要求上并没有差别

**Comment by HyperLife1119** [comment]
好的，感谢。回头我再试试。希望尽快发布v3.0.9正式版😄
