### ISSUE TITLE
3.0.x-dev 开发版报错反馈

### ISSUE THREAD

**Issue by HyperLife1119** [top-think/think-swoole#154]
在执行 `$websocket->to(xxx)->emit(xxx, xxx)` 的时候报错：

```
                                         
  [think\exception\ErrorException]       
  Undefined index: websocket._broadcast  
                                         


Exception trace:
 () at xxxxx/vendor/topthink/think-swoole/src/coroutine/Context.php:90
 think\initializer\Error->appError() at xxxxx/vendor/topthink/think-swoole/src/coroutine/Context.php:90
 think\swoole\coroutine\Context::removeData() at xxxxx/vendor/topthink/think-swoole/src/Websocket.php:226
 think\swoole\Websocket->reset() at xxxxx/vendor/topthink/think-swoole/src/Websocket.php:161
 think\swoole\Websocket->emit() at xxxxx/app/listener/websocket/Message.php:27
 app\listener\websocket\Message->handle() at n/a:n/a
 ReflectionMethod->invokeArgs() at xxxxx/vendor/topthink/framework/src/think/Container.php:327
 think\Container->invokeMethod() at xxxxx/vendor/topthink/framework/src/think/Container.php:360
 think\Container->invoke() at xxxxx/vendor/topthink/framework/src/think/Event.php:260
 think\Event->dispatch() at xxxxx/vendor/topthink/framework/src/think/Event.php:221
 think\Event->trigger() at xxxxx/vendor/topthink/think-swoole/src/concerns/InteractsWithWebsocket.php:91
 think\swoole\Manager->think\swoole\concerns\{closure}() at xxxxx/vendor/topthink/framework/src/think/Container.php:292
 think\Container->invokeFunction() at xxxxx/vendor/topthink/framework/src/think/Container.php:356
 think\Container->invoke() at xxxxx/vendor/topthink/think-swoole/src/Sandbox.php:84
 think\swoole\Sandbox->run() at xxxxx/vendor/topthink/think-swoole/src/concerns/WithApplication.php:112
 think\swoole\Manager->runInSandbox() at xxxxx/vendor/topthink/think-swoole/src/concerns/InteractsWithWebsocket.php:94
```

**Comment by HyperLife1119** [comment]
在并发状态下，仍然出现redis连接池的问题（默认开启了think-swoole自带的cache连接池功能）：

```
PHP Fatal error:  Uncaught Swoole\Error: Socket#78 has already been bound to another coroutine#15, reading of the same socket in coroutine#17 at the same time is not allowed in /xxxxx/vendor/topthink/framework/src/think/cache/driver/Redis.php:116
Stack trace:
#0 /xxxxx/vendor/topthink/framework/src/think/cache/driver/Redis.php(116): Redis->get('SESSION:...')
#1 /xxxxx/app/listener/websocket/BaseListener.php(47): think\cache\driver\Redis->get('SESSION:...')
#2 /xxxxx/app/listener/websocket/Init.php(26): app\listener\websocket\BaseListener->setFdUserPair('32c26cce5c18a1d...')
#3 [internal function]: app\listener\websocket\Init->handle(Array)
#4 /xxxxx/vendor/topthink/framework/src/think/Container.php(327): ReflectionMethod->invokeArgs(Object(app\listener\websocket\Init), Array)
#5 /xxxxx/vendor/topthink/framework/src/think/Container.php(360): think\Container->invokeMethod('handle in /xxxxx/vendor/topthink/framework/src/think/cache/driver/Redis.php on line 116


                                                                                                                                                                                                       
  [think\exception\ErrorException]                                                                                                                                                                     
  Uncaught Swoole\Error: Socket#78 has already been bound to another coroutine#15, reading of the same socket in coroutine#17 at the same time is not allowed in /xxxxx/vendor  
  /topthink/framework/src/think/cache/driver/Redis.php:116                                                                                                                                             
  Stack trace:                                                                                                                                                                                         
  #0 /xxxxx/vendor/topthink/framework/src/think/cache/driver/Redis.php(116): Redis->get('SESSION:...')                                                                   
  #1 /xxxxx/app/listener/websocket/BaseListener.php(47): think\cache\driver\Redis->get('SESSION:...')                                                                    
  #2 /xxxxx/app/listener/websocket/Init.php(26): app\listener\websocket\BaseListener->setFdUserPair('32c26cce5c18a1d...')                                                       
  #3 [internal function]: app\listener\websocket\Init->handle(Array)                                                                                                                                   
  #4 /xxxxx/vendor/topthink/framework/src/think/Container.php(327): ReflectionMethod->invokeArgs(Object(app\listener\websocket\Init), Array)                                    
  #5 /xxxxx/vendor/topthink/framework/src/think/Container.php(360): think\Container->invokeMethod('handle                                                                       
                                                                                                                                                                                                       
```

**Comment by HyperLife1119** [comment]
感谢云哥
