### ISSUE TITLE
如何正确进行事务操作

### ISSUE THREAD

**Issue by HyperLife1119** [top-think/think-swoole#193]
```
// 启动事务
Db::startTrans();
try {
    Db::table('think_user')->find(1);
    Db::table('think_user')->delete(1);
    // 提交事务
    Db::commit();
} catch (\Exception $e) {
    // 回滚事务
    Db::rollback();
}
```
由于使用了数据库连接池，使用以上代码进行事务操作会导致后台报错，想请教一下think-swoole开启连接池后如何正确进行事务操作。

**Comment by HyperLife1119** [comment]
报错如下
```
Uncaught Swoole\Error: Socket#20 has already been bound to another coroutine#39, reading of the same socket in coroutine#38 at the same time is not allowed in /vendor/topthink/think-orm/src/db/PDOConnection.php:1429  
  Stack trace:                                                                                                                                                                                                                                              
  #0 /vendor/topthink/think-orm/src/db/PDOConnection.php(1429): PDO->commit()                                                                                                                                              
  #1 /vendor/topthink/think-orm/src/db/PDOConnection.php(1377): think\db\PDOConnection->commit()             
  #2 /vendor/topthink/think-orm/src/db/concern/Transaction.php(82): think\db\PDOConnection->transaction()                                                                                                                  
  #3 /vendor/topthink/think-orm/src/Model.php(653): think\db\BaseQuery->transaction()                                                                                                                                      
  #4 /vendor/topthink/think-orm/src/Model.php(534): think\Model->updateData()                                                                                                                                              
  #5 /vendor/topthink/think-orm/src/Model.php(872): think\Model->save()                                                                                                                                                                                                                                                                                                                                                                                                                                                       
```

**Comment by yunwuxin** [comment]
你这里 一次查询  一次删除   怎么会执行到`think\Model->save()`这个方法的

**Comment by HyperLife1119** [comment]
排除事务操作的问题，报错如下

```
[2020-12-27 20:25:43 $5940.0]	WARNING	check_worker_exit_status: worker#1[pid=5945] abnormal exit, status=1, signal=0
PHP Fatal error:  Uncaught Swoole\Error: Socket#24 has already been bound to another coroutine#15, reading of the same socket in coroutine#14 at the same time is not allowed in vendor/topthink/think-orm/src/db/PDOConnection.php:741
Stack trace:
#0 vendor/topthink/think-orm/src/db/PDOConnection.php(741): PDO->prepare()
#1 vendor/topthink/think-orm/src/db/PDOConnection.php(688): think\db\PDOConnection->getPDOStatement()
#2 vendor/topthink/think-orm/src/db/PDOConnection.php(886): think\db\PDOConnection->pdoQuery()
#3 vendor/topthink/think-orm/src/db/BaseQuery.php(1090): think\db\PDOConnection->select()
#4 app/core/service/User.php(573): think\db\BaseQuery->select()
#5 app/controller/User.php(112): app\core\service\User::getChatList()
#6 [internal function]: app\controller\User->getChatList()
#7 / in vendor/topthink/think-orm/src/db/PDOConnection.php on line 741
```

`app\core\service\User::getChatList()` 代码链接：https://github.com/HyperLife1119/OnChat/blob/381782047064eb8e11d180759de54ae87481f434/app/core/service/User.php#L540
代码里使用到了阿里云OSS

**Comment by yunwuxin** [comment]
报错的地方 并不一定是有问题的地方    
可能的原因是连接池里的某个连接被你其他地方保存下来了   导致两处同时调用

**Comment by HyperLife1119** [comment]
您看一下是不是这里会出问题？
```
// 这里我在ChatRecordModel里定义了一个静态方法，用于切换表后缀实现分表
public static function opt(int $chatroomId)
{
        $model = new static();
        // 拿到千位数（小于1000，千位数为1）
        $thousand = $chatroomId < 1000 ? 1 : substr((string) $chatroomId, 0, -3);

        $model->setSuffix('_' . $thousand . '_' . $chatroomId % 100);

        return $model;
}

// 调用...
ChatRecordModel::opt($value['chatroom_id'])->where()....
```

**Comment by yunwuxin** [comment]
不是

**Comment by HyperLife1119** [comment]
阿里云OSS被我改成单例模式了，会是这个原因吗？
```
public static function getInstance(): Client
{
        if (!(self::$instance instanceof self)) {
            self::$instance = new self();
        }

        return self::$instance;
}
```

**Comment by yunwuxin** [comment]
建议你仔细阅读下这里
https://wiki.swoole.com/#/coroutine
尤其是下面这个
https://wiki.swoole.com/#/coroutine/notice

不然很容易出问题

**Comment by HyperLife1119** [comment]
好的，谢谢你
