### ISSUE TITLE
Db连接池似乎没有正常工作

### ISSUE THREAD

**Issue by HyperLife1119** [top-think/think-swoole#201]
我并没有保存连接实例，但仍然发生此错误。
测试场景：客户端使用sokcet.io连接到websocket，高频率发射`init`事件到服务器

服务端代码如下
```
// 这是Websocket，Socket.io的一个事件处理类
// 事件名为swoole.websocket.Init，已注册到event.php
class Init
{
   /**
     * 事件监听处理
     *
     * @return mixed
     */
    public function handle($event)
    {
        UserModel::find(1);
    }
}
```

报错如下
```
[error] [1]Uncaught Swoole\Error: Socket#119 has already been bound to another coroutine#7, reading of the same socket in coroutine#10 at the same time is not allowed in /vendor/topthink/think-orm/src/db/PDOConnection.php:568
Stack trace:
#0 /vendor/topthink/think-orm/src/db/PDOConnection.php(568): PDO->__construct('mysql:host=127....', 'onchat', 'Kf7TjkP6NKfs6KH...', Array)
#1 /vendor/topthink/think-orm/src/db/PDOConnection.php(529): think\db\PDOConnection->createPdo('mysql:host=127....', 'onchat', 'Kf7TjkP6NKfs6KH...', Array)
#2 /vendor/topthink/think-orm/src/db/PDOConnection.php(1653): think\db\PDOConnection->connect()
#3 /vendor/topthink/think-orm/src/db/PDOConnection.php(732): think\db\PDOConnection->initConnect(false)
#4 /vendor/topthink/think-orm/src/db/PDOConnection.php(688): think\db\PDOConnection->getPDOStatement('SELECT * FROM `...', Arra[/vendor/topthink/think-orm/src/db/PDOConnection.php:568]
```

**Comment by HyperLife1119** [comment]
用与上面同样的测试方法，cache连接池并不会出现该问题

**Comment by yunwuxin** [comment]
我刚测试了  没有发现这个问题 
这是你报错的地方  不一定是连接没有回收的地方  
可能是其他地方导致链接没回收  然后这里又去使用这个连接了  导致出错了

**Comment by HyperLife1119** [comment]
我的Db查询都是通过模型静态直接调用的，也没有保存起来复用，实在想不到是哪里的问题😢

**Comment by yunwuxin** [comment]
不一定是保存  可能是哪里内存泄漏了  没有释放

**Comment by HyperLife1119** [comment]
好的，我再回去看看😭

**Comment by HyperLife1119** [comment]
我发现这个问题只有在高频率发送socket.io事件的时候才触发；高频率发送HTTP请求，并不会出现该问题。
可以请教一下，我应该如何调试这个问题呢？可以较为精确的定位到出问题的代码

**Comment by yunwuxin** [comment]
昨天websocket的socket.io 的相关功能有个比较大的更新 用法有些改变  可以用新版试试

**Comment by HyperLife1119** [comment]
更新之后，之前写的socket.io事件都没有被触发；

**Comment by HyperLife1119** [comment]
我的问题依然存在，我不知道应该如何调试，找到出问题的代码😭

**Comment by yunwuxin** [comment]
新的socket.io 只是最新的3.0版本   所有的socket.io事件 都是触发 event事件  在这个里面自己做不同类型的处理   完善了connect事件

**Comment by HyperLife1119** [comment]
嗯，我刚才在阅读源码的时候看到了；
用了新版websocket之后，我仍然出现 `Sockethas already been bound to another coroutine` 的问题，
所以问题是出现在我的业务代码中的，那么我应该如何调试代码？才可以找到问题代码

**Comment by yunwuxin** [comment]
你本地的话 去掉不相关的功能  最小化排查

**Comment by HyperLife1119** [comment]
好吧，谢谢你😭

**Comment by HyperLife1119** [comment]
问题终于解决了；
原来是我开启了DB连接参数 `PDO::ATTR_PERSISTENT` 所导致的
