### ISSUE TITLE
think\initializer\Error->appShutdown() 

### ISSUE THREAD

**Issue by wasdujk** [top-think/think-swoole#217]
版本 topthink/think-swoole               v3.0.8 

完整错误日志如下
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /www/wwwroot/test.com/vendor/lizhichao/word/Lib/VicWord.php on line 44
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /www/wwwroot/test.com/vendor/topthink/framework/src/think/initializer/Error.php on line 87
PHP Fatal error:  Uncaught Error: Call to a member function make() on null in /www/wwwroot/test.com/vendor/topthink/think-swoole/src/concerns/InteractsWithPools.php:25
Stack trace:
#0 /www/wwwroot/test.com/vendor/topthink/think-swoole/src/concerns/InteractsWithPools.php(50): think\swoole\Manager->getPools()
#1 /www/wwwroot/test.com/vendor/topthink/framework/src/think/Container.php(292): think\swoole\Manager->think\swoole\concerns\{closure}()
#2 /www/wwwroot/test.com/vendor/topthink/framework/src/think/Container.php(356): think\Container->invokeFunction(Object(Closure), Array)
#3 /www/wwwroot/test.com/vendor/topthink/framework/src/think/Event.php(260): think\Container->invoke(Object(Closure), Array)
#4 /www/wwwroot/test.com/vendor/topthink/framework/src/think/Event.php(221): think\Event->dispatch(Object(Closure), Array)
#5 /www/wwwroot/test.com/vendor/topthink/think-swoole/src/concerns/WithApplication.php(45): think\Event->trigger('swoole.workerEr...', in /www/wwwroot/test.com/vendor/topthink/think-swoole/src/concerns/InteractsWithPools.php on line 25

                                                                                                                                                                    
  [think\exception\ErrorException]                                                                                                                                  
  Uncaught Error: Call to a member function make() on null in /www/wwwroot/test.com/vendor/topthink/think-swoole/src/concerns/InteractsWithPools.php:25  
  Stack trace:                                                                                                                                                      
  #0 /www/wwwroot/test.com/vendor/topthink/think-swoole/src/concerns/InteractsWithPools.php(50): think\swoole\Manager->getPools()                        
  #1 /www/wwwroot/test.com/vendor/topthink/framework/src/think/Container.php(292): think\swoole\Manager->think\swoole\concerns\{closure}()               
  #2 /www/wwwroot/test.com/vendor/topthink/framework/src/think/Container.php(356): think\Container->invokeFunction(Object(Closure), Array)               
  #3 /www/wwwroot/test.com/vendor/topthink/framework/src/think/Event.php(260): think\Container->invoke(Object(Closure), Array)                           
  #4 /www/wwwroot/test.com/vendor/topthink/framework/src/think/Event.php(221): think\Event->dispatch(Object(Closure), Array)                             
  #5 /www/wwwroot/test.com/vendor/topthink/think-swoole/src/concerns/WithApplication.php(45): think\Event->trigger('swoole.workerEr...',                 
                                                                                                                                                                    

Exception trace:
 () at /www/wwwroot/test.com/vendor/topthink/think-swoole/src/concerns/InteractsWithPools.php:25
 think\initializer\Error->appShutdown() at n/a:n/a

PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /www/wwwroot/test.com/vendor/lizhichao/word/Lib/VicWord.php on line 44
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /www/wwwroot/test.com/vendor/topthink/framework/src/think/initializer/Error.php on line 87

**Comment by wasdujk** [comment]
是memory_limit过小导致的问题，与依赖无关
