### ISSUE TITLE
执行 php think swoole restart 直接报错

### ISSUE THREAD

**Issue by xaboy** [top-think/think-swoole#222]
swoole: `4.5.9`
think-swoole: `v3.1.2`

执行 `php think swoole restart`直接报错

```log
Starting swoole http server...
Swoole http server started: <http://0.0.0.0:8324>
You can exit with `CTRL-C`
PHP Fatal error:  Uncaught Error: Call to undefined function Smf\ConnectionPool\go() in /xxxx/vendor/open-smf/connection-pool/src/ConnectionPool.php:92
Stack trace:
#0 /xxxx/vendor/topthink/think-swoole/src/pool/Proxy.php(69): Smf\ConnectionPool\ConnectionPool->init()
#1 /xxxx/vendor/topthink/think-swoole/src/pool/Cache.php(13): think\swoole\pool\Proxy->__construct(Object(Closure), Array)
#2 /xxxx/vendor/topthink/framework/src/think/Manager.php(65): think\swoole\pool\Cache->createDriver('redis')
#3 /xxxx/vendor/topthink/framework/src/think/Manager.php(55): think\Manager->getDriver('redis')
#4 /xxxx/vendor/topthink/framework/src/think/Cache.php(90): think\Manager->driver('redis')
#5 /xxxx/vendor/topthink/framework/src/think/Db.php(38): think\Cache->store(NULL)

```
@yunwuxin 

解决方法

将`vendor/open-smf/connection-pool/src/ConnectionPool.php`文件`92`行的 `go` 方法修改为:
```php
\Swoole\Coroutine::create
```

**Comment by sy-records** [comment]
更新下`open-smf/connection-pool`依赖

**Comment by xaboy** [comment]
我从`3.0.8`版本分别更新到`3.0.10`和`3.1.x`然后开启服务,几秒钟后都会自动挂掉然后一大堆报错. 是不是新版本中都没有考虑向下兼容的问题 @sy-records
