### ISSUE TITLE
bug: 升级到think-swoole v4.0 后无法使用socket.io连接

### ISSUE THREAD

**Issue by HyperLife1119** [top-think/think-swoole#250]
使用 `php think swoole` 启动服务器，控制台死循环报错：

```bash
PHP Fatal error:  Uncaught InvalidArgumentException: method param miss:host in /mnt/d/xxxxx/vendor/topthink/framework/src/think/Container.php:458
Stack trace:
#0 /mnt/d/xxxxx/vendor/topthink/framework/src/think/Container.php(392): think\Container->bindParams()
#1 /mnt/d/xxxxx/vendor/topthink/framework/src/think/Container.php(251): think\Container->invokeClass()
#2 /mnt/d/xxxxx/vendor/topthink/framework/src/think/Container.php(497): think\Container->make()
#3 /mnt/d/xxxxx/vendor/topthink/framework/src/think/Container.php(448): think\Container->getObjectParam()
#4 /mnt/d/xxxxx/vendor/topthink/framework/src/think/Container.php(322): think\Container->bindParams()
#5 /mnt/d/xxxxx/vendor/topthink/framework/src/think/Container.php(361): think\Container->invokeMethod()
#6 /mnt/d/xxxxx/vendor/topthink/framework/src/think/Event.php(260): think\Container->invoke()
#7 /mnt/d/xxxxx/vendor/ in /mnt/d/xxxxx/vendor/topthink/framework/src/think/Container.php on line 458
```

```bash
PHP Fatal error:  Uncaught Swoole\Error: API must be called in the coroutine in /mnt/d/xxxxx/vendor/topthink/framework/src/think/console/output/driver/Console.php:203
Stack trace:
#0 /mnt/d/xxxxx/vendor/topthink/framework/src/think/console/output/driver/Console.php(203): proc_open()
#1 /mnt/d/xxxxx/vendor/topthink/framework/src/think/console/output/driver/Console.php(180): think\console\output\driver\Console->getSttyColumns()
#2 /mnt/d/xxxxx/vendor/topthink/framework/src/think/console/output/driver/Console.php(145): think\console\output\driver\Console->getTerminalDimensions()
#3 /mnt/d/xxxxx/vendor/topthink/framework/src/think/console/output/driver/Console.php(82): think\console\output\driver\Console->getTerminalWidth()
#4 /mnt/d/xxxxx/vendor/topthink/framework/src/think/console/Output.php(167): think\console\output\driver\Console->renderException()
#5 /mnt/d/xxxxx/vendor/topthink/framework/src/think/exception in /mnt/d/xxxxx/vendor/topthink/framework/src/think/console/output/driver/Console.php on line 203
```

配置文件：
```php
return [
    'http'       => [
        'enable'     => true,
        'host'       => env('server.host', '127.0.0.1'),
        'port'       => env('server.port', 9501),
        'worker_num' => swoole_cpu_num() * 2,
    ],
    'websocket'  => [
        'enable'        => true,
        'handler'       => Handler::class,
        'ping_interval' => 25000,
        'ping_timeout'  => 60000,
        'room'          => [
            'type'  => 'table',
            'table' => [
                'room_rows'   => 4096,
                'room_size'   => 2048,
                'client_rows' => 8192,
                'client_size' => 2048,
            ],
            'redis' => [
                'host'          => env('redis.host', '127.0.0.1'),
                'port'          => env('redis.port', 6379),
                'password'      => env('redis.password', ''),
                'select'        => env('redis.database', 0),
                'max_active'    => 3,
                'max_wait_time' => 5,
            ],
        ],
        'listen'        => [],
        'subscribe'     => [],
    ],
    'rpc'        => [
        'server' => [
            'enable'     => false,
            'host'       => '0.0.0.0',
            'port'       => 9000,
            'worker_num' => swoole_cpu_num() * 2,
            'services'   => [],
        ],
        'client' => [],
    ],
    //队列
    'queue'      => [
        'enable'  => false,
        'workers' => [],
    ],
    'hot_update' => [
        'enable'  => env('APP_DEBUG', false),
        'name'    => ['*.php'],
        'include' => [app_path()],
        'exclude' => [],
    ],
    //连接池
    'pool'       => [
        'db'    => [
            'enable'        => true,
            'max_active'    => 100,
            'max_wait_time' => 5,
        ],
        'cache' => [
            'enable'        => true,
            'max_active'    => 100,
            'max_wait_time' => 5,
        ],
        //自定义连接池
    ],
    'tables'     => [
        'user' => [
            'size'    => 8192,
            'columns' => [
                [
                    'name' => 'id',
                    'type' => Table::TYPE_INT,
                    'size' => 4
                ],
                [
                    'name' => 'username',
                    'type' => Table::TYPE_STRING,
                    'size' => 30
                ]
            ]
        ],
        'fd' => [
            'size'    => 8192,
            'columns' => [
                [
                    'name' => 'fd',
                    'type' => Table::TYPE_INT,
                    'size' => 4
                ],
            ]
        ],
        'throttle' => [
            'size'    => 8192,
            'columns' => [
                [
                    'name' => 'time',
                    'type' => Table::TYPE_INT,
                    'size' => 8
                ],
                [
                    'name' => 'count',
                    'type' => Table::TYPE_INT,
                    'size' => 1
                ],
            ]
        ]
    ],
    //每个worker里需要预加载以共用的实例
    'concretes'  => [],
    //重置器
    'resetters'  => [],
    //每次请求前需要清空的实例
    'instances'  => [],
    //每次请求前需要重新执行的服务
    'services'   => [],
];
```

**Comment by yunwuxin** [comment]
你应该是有地方依赖注入了3.0的\Swoole\Server对象了 这个4.0里不存在了

**Comment by HyperLife1119** [comment]
是的，有几个地方依赖注入\Swoole\Server了，回头改一下再试试。

**Comment by HyperLife1119** [comment]
无法连接socket.io

```js
s = io('http://localhost:9501/', {transports: ['websocket']});
s.on("connection", (socket) => {
  console.log(socket.handshake.query);
});
```
![image](https://user-images.githubusercontent.com/41798664/120675704-e4238080-c4c7-11eb-845a-b32a196c79e5.png)

**Comment by yunwuxin** [comment]
Messages里是啥   websocket服务启动了吗

**Comment by HyperLife1119** [comment]
message里面啥也没有，websocket连接是直接被finish了
websocket已是开启状态，上面我也发了config配置

**Comment by yunwuxin** [comment]
服务端没有错误信息？

**Comment by HyperLife1119** [comment]
服务器没有任何报错。
这是message
![image](https://user-images.githubusercontent.com/41798664/120733648-28d80780-c51a-11eb-88a5-8d0a99b36e6b.png)
![image](https://user-images.githubusercontent.com/41798664/120733682-35f4f680-c51a-11eb-9f37-fd5e1017de37.png)

**Comment by HyperLife1119** [comment]
websocket似乎确实是没开起来，`websocket.enable` 配置无效
https://github.com/top-think/think-swoole/blob/61c4b9fb6e996f0ab74d83594169498b08cbda61/src/concerns/InteractsWithWebsocket.php#L36 这个$wsEnable变量似乎没有被使用到

**Comment by yunwuxin** [comment]
在InteractsWithHttp里使用的

**Comment by HyperLife1119** [comment]
刚刚重新开了个项目，试了一下还是不行

**Comment by yunwuxin** [comment]
我们有项目正式已经在使用了，都是正常的

**Comment by yunwuxin** [comment]
你不用socket.io  直接在控制台里使用
```
new WebSocket("ws://localhost:9501")
```

看看能不能连上

**Comment by HyperLife1119** [comment]
路由：
```php
Route::get('/', function () {
    return '
    <script src="https://cdn.socket.io/4.1.1/socket.io.min.js" integrity="sha384-cdrFIqe3RasCMNE0jeFG9xJHog/tgOVC1E9Lzve8LQN1g5WUHo0Kvk1mawWjxX7a" crossorigin="anonymous"></script>
    <script>
    var s = io("ws://localhost", {transports: ["websocket"]});
    s.on("connection", (socket) => {
        console.log(socket.handshake.query);
    });
    </script>
    ';
});
```

```php
<?php

use think\swoole\websocket\socketio\Handler;

return [
    'http'       => [
        'enable'     => true,
        'host'       => '0.0.0.0',
        'port'       => 80,
        'worker_num' => swoole_cpu_num(),
    ],
    'websocket'  => [
        'enable'        => true,
        'handler'       => Handler::class,
        'ping_interval' => 25000,
        'ping_timeout'  => 60000,
        'room'          => [
            'type'  => 'table',
            'table' => [
                'room_rows'   => 4096,
                'room_size'   => 2048,
                'client_rows' => 8192,
                'client_size' => 2048,
            ],
            'redis' => [
                'host'          => '127.0.0.1',
                'port'          => 6379,
                'max_active'    => 3,
                'max_wait_time' => 5,
            ],
        ],
        'listen'        => [],
        'subscribe'     => [],
    ],
    'rpc'        => [
        'server' => [
            'enable'     => false,
            'host'       => '0.0.0.0',
            'port'       => 9000,
            'worker_num' => swoole_cpu_num(),
            'services'   => [],
        ],
        'client' => [],
    ],
    //队列
    'queue'      => [
        'enable'  => false,
        'workers' => [],
    ],
    'hot_update' => [
        'enable'  => env('APP_DEBUG', false),
        'name'    => ['*.php'],
        'include' => [app_path()],
        'exclude' => [],
    ],
    //连接池
    'pool'       => [
        'db'    => [
            'enable'        => true,
            'max_active'    => 3,
            'max_wait_time' => 5,
        ],
        'cache' => [
            'enable'        => true,
            'max_active'    => 3,
            'max_wait_time' => 5,
        ],
        //自定义连接池
    ],
    'tables'     => [],
    //每个worker里需要预加载以共用的实例
    'concretes'  => [],
    //重置器
    'resetters'  => [],
    //每次请求前需要清空的实例
    'instances'  => [],
    //每次请求前需要重新执行的服务
    'services'   => [],
];

```

**Comment by HyperLife1119** [comment]
> 你不用socket.io 直接在控制台里使用
> 
> ```
> new WebSocket("ws://localhost:9501")
> ```
> 
> 看看能不能连上

不能
```
new WebSocket("ws://localhost")
WebSocket {url: "ws://localhost/", readyState: 0, bufferedAmount: 0, onopen: null, onerror: null, …}
VM72:1 WebSocket connection to 'ws://localhost/' failed: 
```

**Comment by HyperLife1119** [comment]
swoole:
```
swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.6.7
Built => Jun  3 2021 22:56:17
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.0.2r  26 Feb 2019
pcre => enabled
zlib => 1.2.11
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
```

**Comment by yunwuxin** [comment]
你是什么环境    有用nginx代理吗

**Comment by HyperLife1119** [comment]
> 你是什么环境 有用nginx代理吗

WSL Ubuntu，开发环境，没有nginx代理

**Comment by yunwuxin** [comment]
知道原因了，我们用nginx代理后没问题，不用nginx代理会连接失败

我确认下是不是swoole的问题

**Comment by HyperLife1119** [comment]
好的，

**Comment by yunwuxin** [comment]
修正了

**Comment by HyperLife1119** [comment]
升级之后，使用new WebSocket("ws://localhost:9501")可以连接上，但使用socket.io.js就无法连接了，情况跟之前一样

**Comment by yunwuxin** [comment]
还没有错误信息吗

**Comment by HyperLife1119** [comment]
没有

**Comment by yunwuxin** [comment]
socket.io 连接的时候 Messages里应该有信息吧

**Comment by HyperLife1119** [comment]
没有信息，情况跟之前的一样。

使用new WebSocket("ws://localhost:9501")连接的话，就正常，有收到消息：
![image](https://user-images.githubusercontent.com/41798664/120748477-6e55fe00-c535-11eb-8771-5c7c142a16f3.png)

**Comment by HyperLife1119** [comment]
另外，stop，reload等指令是不支持了吗？守护进程模式也没有看到

**Comment by yunwuxin** [comment]
检查下socket.io连接时的端口和域名  

new WebSocket能连上 就说明websocket服务是正常的

**Comment by HyperLife1119** [comment]
> 检查下socket.io连接时的端口和域名
> 
> new WebSocket能连上 就说明websocket服务是正常的

不好意思，刚才检查了一下，端口错了，现在可以了👍

**Comment by HyperLife1119** [comment]
问一下：stop，reload等指令是不支持了吗？守护进程模式也没有看到

**Comment by yunwuxin** [comment]
> 另外，stop，reload等指令是不支持了吗？守护进程模式也没有看到

不支持，建议使用supervisor来管理进程

**Comment by HyperLife1119** [comment]
> > 另外，stop，reload等指令是不支持了吗？守护进程模式也没有看到
> 
> 不支持，建议使用supervisor来管理进程

好嘞
