### ISSUE TITLE
Task执行异常

### ISSUE THREAD

**Issue by edenleung** [top-think/think-swoole#44]
在v2.0.13版本里，在已运行服务的情况下，使用Task跟直接调用容器里的swoole的时候，均发现
~~~
  [think\exception\ErrorException]
  Uncaught think\exception\ClassNotFoundException: class not exists: swoole in /home/liang/tp5/thinkphp/library/think/Cont
  ainer.php:442
  Stack trace:
  #0 /home/liang/tp5/thinkphp/library/think/Container.php(284): think\Container->invokeClass('swoole', Array)
  #1 /home/liang/tp5/thinkphp/library/think/Container.php(132): think\Container->make('swoole', Array, false)
  #2 /home/liang/tp5/vendor/topthink/think-swoole/src/Task.php(33): think\Container::get('swoole')
  #3 [internal function]: think\swoole\Task->async(Object(think\swoole\SuperClosure))
  #4 /home/liang/tp5/thinkphp/library/think/Facade.php(123): call_user_func_array(Array, Array)
  #5 /home/liang/tp5/application/server/controller/Socketserver.php(47): think\Facade::__callStatic('async', Array)
  #6 [internal function]: app\server\controller\SocketServer->task(Object(stdClass))
  #7 /home/liang/tp5/application/server/controller/Socketserver.php(27): call_user_func(Array, Object(stdClass))
  #8 {main}
    thrown
~~~

事例
~~~
Task::async(function($serv, $task_id, $data){
            $i = 0;
            while ($i < 10) {
                $i++;
                echo $i;
                sleep(1);
            }
        });
~~~

**Comment by 125522311** [comment]
同问

**Comment by xavieryang007** [comment]
并没有出现如上问题，请问启动的是swoole还是swoole:server，目前很多功能都是针对swoole而非swoole:server,已经计划下一步推出websocket

**Comment by xavieryang007** [comment]
另外你的服务是自定义的么？

**Comment by 125522311** [comment]
启动的是自定的swoole:server服务，
退出websocket。。。。这是为什么啊？

**Comment by xavieryang007** [comment]
目前主要功能都在swoole命令，swoole：server不具备该功能 上面打错字了，已经修改。

**Comment by 125522311** [comment]
好的，好的。多谢耐心回复

**Comment by xavieryang007** [comment]
是否需要websocket或者tcp服务，不需要则启动 php think swoole启动服务

**Comment by 125522311** [comment]
我需要websocket的 需要长连接

**Comment by xavieryang007** [comment]
目前websocket版不支持，下个版本会支持，会合并websocket和http

**Comment by xavieryang007** [comment]
明天我提交下代码，可以先用测试版

**Comment by 125522311** [comment]
好的，期待大神。(●'◡'●)

**Comment by edenleung** [comment]
@xavieryang007 
我的情况是在自定义，没尝试在php think swoole, php think swoole:server中尝试。

**Comment by edenleung** [comment]
是否确定上述的问题，在php think swoole里没问题。如果是，我尝试不使用自定义

**Comment by xavieryang007** [comment]
@saybabi  你可以自己试下，php think swoole下没有问题，目前php think swoole模式只是HTTP方式

**Comment by edenleung** [comment]
php think swoole 暂时不支持websocket是吧？

**Comment by xavieryang007** [comment]
php think swoole目前不支持websocket

**Comment by edenleung** [comment]
我本地直接运行 php think swoole 异常(没改任何代码)
运行环境: cygwin
~~~
$ php think swoole
Starting swoole http server...
[2018-10-26 15:50:53 @7136.0]   WARNING swShareMemory_mmap_create: mmap(13009051392) failed. Error: Resource temporarily unavailable[11]
PHP Fatal error:  Swoole\Table::create(): unable to allocate memory. in /home/Administrator/tp5/vendor/topthink/think-swoole/src/CacheTable.php on line 33
~~~

**Comment by saybabi** [comment]
运行环境: `cygwin`

**Comment by xavieryang007** [comment]
![image](https://user-images.githubusercontent.com/6174650/47552539-86098680-d937-11e8-8174-d0011627cf68.png)
那个地方去掉参数10

**Comment by xavieryang007** [comment]
或者自己配置cache_size

**Comment by xavieryang007** [comment]
提示是无法开辟足够的内存

**Comment by edenleung** [comment]
OK, 完美运行

**Comment by xavieryang007** [comment]
Websocket 可以参考这个，这个已经提交过来了，可以用dev

**Comment by edenleung** [comment]
@xavieryang007  Good Job! 👍
